STSRT_BOT_MSG = 'Бот начал работу'
CHEK_TOKEN = 'Работает функция проверки токенов'
SEND_MSG_TG = 'Отправляем сообщение в Telegram'
SEND_MSG_OK = 'Сообщение отправлено'
STATUS_WOMEWORK_NOT_CHANGE = 'Статус домашних работ не поменялся.'
STATUS_WOMEWORK_CHANGE = 'Изменился статус проверки работы '

ERROR_PROGRAM_FAILURE = 'Сбой в работе программы: '
ERROR_NOT_REQUIRED_VARIABLES = 'Отсутствуют обязательные переменные.'
ERROR_SEND_MSG = 'Cбой при отправке сообщения в Telegram'
ERROR_GET_ENDPOINT = 'Произошел сбой при запросе к эндпоинту'
ERROR_CONNECT_SERVER = 'Ошибка подключения к серверу status code: '
ERROR_NOT_200 = 'Код отличный от 200: '
ERROR_GET_API = 'Возникли проблемы с запросом API, статус запроса '
ERROR_GET_NOT_KEY_HOMEWORKS = 'В запросе отсутствует ключ "homeworks"'
ERROR_GET_NOT_KEY_HOMEWORK_NAME = "Ключ 'homework_name' отсутствует в списке"
ERROR_GET_NOT_KEY_STATUS = 'Ключ "status" отсутствует в списке'
ERROR_NOT_VERDICTS_FOR_STATUS = ('Вердикт отсутствует для '
                                 'данного статуса домашней работы')
ERROR_HOMEWORKS_NOT_LIST = 'Домашки пришли не в виде списка'
ERROR_HOMEWORKS_NOT_DICT = 'Домашки пришли не в виде словаря'
